apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: fixed-ubuntu
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command: ['sh', '-c', 'tail -F /tmp/test']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
