apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - image: httpd
    name: c1
  - name: c2 
    image: busybox
    command: ['sh', '-c', 'echo "Sleeping 1h because I am tired"; sleep 3600']
