apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user-request-devops
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0daR1YyYjNCek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQW5ER2hxZGNxNnFFSDZUcHFrK0E4aTZDbGxORUM1QU1CUXBZaWZIMDlJb1FXCkNJR2k2OHRLUXdHK09obGJVRnVVZytWWGN5RXIzTXk1RXArd2pkR2g4NW9JMmxUTzZhQy92eGhKQjZldkJHaFQKMGhPb2F1dDExS2VkTzdOWjNHVk5UTzFQYzBnWG1jb0Y1L2dWYmUyU21LRTM4TjBXYUxFaGtMRGJVdWVwc1pnNwplanhWV0Y5cC8wakorb2NycGh6TnFyZmFNN2FFYjlmYVpyajlFYjNaSWtabktnN3dkeTA4Ymo0aUU0S3UrWUFtClZDemxpVVhMc05VOU5DV1pVSzh3QlZFVHE4V3dkUm1Ud0l4bDRrZFZUY2tXbkU0TzIxRVFmRDRMVUd5ODJiWm0KaGZnazdFaUpPaGRjWlQxcTg0TDBPcDJiaVV5N0dNeEIyRmphekNYbmFRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRXN3RG95MUhqNUFlOXIyc244SE9oRHFzd3Z6Z0JLVTRiM1B2T3hsMXZzSkZINVJxR05tCkFqM1RuSEpPK1ljNWF5V0N4SEhJalRwYlluOFdPNmcvSFdIMkZPZlJwbDFOUW5RNWtndDVROTBFSkJwZ005eVEKaVpRMlBSQUd3UlQvMldMZ1RRZVo2SHJpWmR5NnEwb2dSRDJoc29VTk5YUkpQQU51cWZoODJISXRveHhDMXlORwptcHNrWGdpaTNyL3Y2UkZlcWxtaWRrZURWZWVGV3Q3Z1pvNkRRTEdBcndEaUdNQnZmeU1LT1pQRUcxK0txWHRuCmlwMWhReGVLQjNHSzBNN1RMUFNPWFdQaHNhNlF2bTU5NEs1ajJCdzd4Zk1iaE12eUZhWDdyTmdKcnFjQ0s0RFoKTEFYakZ4SjZaMllPSDhvbDEwQmVvbDlnZitIODVyWmFWOUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo= 
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 315569260
  usages:
  - digital signature
  - key encipherment
  - client auth
