apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  nodeName: worker1
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: storage



