apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
spec:
  containers:
  - image: httpd
    name: web-httpd
  tolerations:
  - key: "kubernetes.io/az"
    operator: "Exists"
    effect: "NoSchedule"
